Use Graspi as Module
materialsinnovation/pymks pull request #553
Opened 2021-05-25 16:50 UTC by wd15

Integrate GraSPI into PyMKS.

Check list:

 - [x] Nix build works
 - [ ] pip build won't work as boost can't be added. Boost needs to be optional for pip and turn off graph descriptors in that case
 - [ ] will the documentation build without Boost
 - [ ] still need to make a conda build
 - [ ] create API documentation
 - [ ] conda build

2021-07-07 01:15 UTC, wd15 commented
@beyucel @auag92 this is the rewored Graspi branch using Graspi as a separate importable module. Please review when you get a chance.

2021-07-13 15:16 UTC, beyucel requested changes
- I would add "[None] generates an extra dimension at the first axis." Line 4
- I would remove "threads_per_worker=2"  Line 5
- 'dask-report.html' not showing anything Line 19

2021-07-14 21:46 UTC, wd15 commented
@beyucel: should be good now, please take a look again

@auag92: please take a look if you get chance

2021-07-15 18:48 UTC, beyucel approved these changes

2021-07-15 18:50 UTC, merged

2021-07-15 18:50 UTC, auag92 approved these changes